### ISSUE TITLE
Allow --schema parameter on tenant generate

### ISSUE THREAD

**Issue by 364734461** [Errorname/prisma-multi-tenant#47] opened 2020-08-14 08:35 UTC
Now I want to pass through `prisma generate --schema="***"` to implement custom directories. (schema.prisma)

But....code....
```ts
  async generateTenants(prismaArgs = '') {
    const schemaPath = await getSchemaPath()
    await runDistantPrisma(`generate ${prismaArgs} --schema ${schemaPath}`)
  }
```
You can open the parameters？

like this
```shell
npx prisma-multi-tenant generate -- --schema=\"./prisma/schemas/one.prisma\""
```
....

**Comment by Errorname** [comment] 2020-08-14 09:22
Hi, thank you for raising this issue!

This would indeed be better to allow to pass --schema when generating tenants. I'll try to work on this feature request, and implement it for the next release of prisma-multi-tenant (probably this week end)

**Comment by Errorname** [comment] 2020-08-16 15:11
The `--schema` has been implemented and released in prisma-multi-tenant@**2.3.1**

**Closed by Errorname** 2020-08-16 15:11 UTC

**Comment by 364734461** [comment] 2020-08-17 03:12
runLocal Error:
![image](https://user-images.githubusercontent.com/16712324/90353854-06076000-e07a-11ea-9955-a543e9000f75.png)
![image](https://user-images.githubusercontent.com/16712324/90353875-1a4b5d00-e07a-11ea-917b-9e305965b30d.png)

Lead to

![image](https://user-images.githubusercontent.com/16712324/90353948-5383cd00-e07a-11ea-89be-c8cd01f4bbda.png)

**Comment by Errorname** [comment] 2020-08-17 07:38
What command where you running ? Does @prisma-multi-tenant/shared is present in your node_modules ? (It should be a dependency of @prisma-multi-tenant/client)

**Comment by 364734461** [comment] 2020-08-17 07:58
RUN `npm run gen`....... package.json scripts => `npx prisma-multi-tenant generate --schema=\"./prisma/one.prisma\"`

```json
"dependencies": {
 "prisma-multi-tenant": "2.3.1",
    "@prisma-multi-tenant/client": "2.3.1",
    "@prisma-multi-tenant/shared": "2.3.1"
}
```

There are ‘< project >/node_modules/@prisma-multi-tenant/shared ’

**Comment by Errorname** [comment] 2020-08-17 08:01
Can you try removing "npx" in the npm script ?

**Comment by 364734461** [comment] 2020-08-17 08:07
Error again！

**Comment by Errorname** [comment] 2020-08-17 08:08
Unfortunately, I am not able to reproduce. Can you make a small reproduction repository so that I can take a look?

**Comment by 364734461** [comment] 2020-08-17 08:25
I seem to have found the problem, which can occur if you install dependencies using PNPM in your project.

```json
{
  "name": "pmt-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "clean": "rm -rf node_modules",
    "generate": "prisma-multi-tenant generate --schema=\"./prisma/one.prisma\""
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "prisma-multi-tenant": "2.3.1",
    "@prisma-multi-tenant/client": "2.3.1",
    "@prisma-multi-tenant/shared": "2.3.1"
  }
}

```

```
pnpm install
```

**Comment by 364734461** [comment] 2020-08-17 08:59
I think the problem may be related to the `pnpm install`.
I've adjusted the dependencies, and that's OK.

But you might want to look at why is the `pnpm` problematic.

https://github.com/364734461/pmt-test

RUN examples/prisma-cli-404 -> npm run generate -> will `Error: Cannot find @prisma/cli`

RUN examples/pmt ->  npm run generate -> will ```Error: Command failed: node "/Users/xxx/pmt-test/examples/pmt/node_modules/@prisma/cli/build/index.js" generate
Environment variables loaded from prisma/.env
Error: Either provide --schema or make sure that you are in a folder with a schema.prisma file.```

**Comment by Errorname** [comment] 2020-08-17 09:12
Great to hear it's working for you.

Yes, it looks like pnpm is doing something that prisma-multi-tenant isn't built to handle. I'll probably look at how Prisma [handled this](https://github.com/prisma/prisma/blob/c36c1a7a84a5be3fd12522870a2f48cabdb6b833/src/packages/client/src/generation/generateClient.ts)
